# Generated by Django 2.0.5 on 2019-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WHEATER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pressure', models.IntegerField()),
                ('Temperature', models.IntegerField()),
            ],
        ),
    ]
