# Generated by Django 2.0.5 on 2019-06-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WHEATER',
            new_name='WEATHER',
        ),
    ]
